In [1]:
import numpy as np

In [2]:
# row * col
a = np.array([[10, 20, 30],[1, 2, 3]])

In [3]:
a

array([[10, 20, 30],
       [ 1,  2,  3]])

In [4]:
a.shape

(2, 3)

In [5]:
np.sum(a,axis=0)

array([11, 22, 33])

In [6]:
# Always remeber to reshape, Don't work with rank #1 matrices
np.sum(a,axis=0).shape

(3,)

In [7]:
# Output is row vector
np.sum(a,axis=0).reshape(1,3)

array([[11, 22, 33]])

In [8]:
np.sum(a,axis=1)

array([60,  6])

In [9]:
np.sum(a,axis=1).shape

(2,)

In [12]:
# Output is col vector
np.sum(a,axis=1).reshape(2,1)

array([[60],
       [ 6]])

In [13]:
a = np.random.rand(3,1)

In [14]:
# Coloum Vector
a

array([[ 0.98228564],
       [ 0.46773212],
       [ 0.17529722]])

In [15]:
a = a.reshape(1,3)

In [16]:
# Row Vector
a

array([[ 0.98228564,  0.46773212,  0.17529722]])